### ISSUE TITLE
How can add participant as listener

### ISSUE THREAD

**Issue by asadumair** [dolbyio-samples/comms-sdk-react-native-getting-started#9]
in documentation there is listen() method to add participitant as listner but this is not present in sdk only join is there so how can i join as a listner?

**Comment by FabienLavocat** [comment]
Thank you @asadumair for your question, we also have received your support request. Are you targeting React Native or Cordova?
The React Native SDK has a [listen](https://github.com/DolbyIO/comms-sdk-react-native/blob/main/src/services/conference/ConferenceService.ts#L150-L162) function.
The Cordova plugin is what we call a UXKit, it is a fully ready to go application (not an SDK) and it does not have the `listen` capability.
